### ISSUE TITLE
Permission to use the code

### ISSUE THREAD

**Issue by blublinsky** [Piyushdharkar/Collaborative-Filtering-Using-Keras#1]
Hi Piyush,
We are writing a book on using Kubeflow for data scientists and would like to use parts of your code - this project. Can we, please, get your permission for this?

**Comment by Piyushdharkar** [comment]
I'd be honored. Please share the book once you're done. I'm genuinely interested.

**Comment by Piyushdharkar** [comment]
> Hi Piyush,
> We are writing a book on using Kubeflow for data scientists and would like to use parts of your code - this project. Can we, please, get your permission for this?

I'd be honored. Please share the book once you're done. I'm genuinely interested.
